development:
  adapter: postgresql
  encoding: unicode
  database: demo_development
  pool: 5
  username: demo
  password: demo
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: demo_test
  pool: 5
  username: demo
  password: demo
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: demo_production
  pool: 5
  username: demo
  password: demo
  host: localhost
